### ISSUE TITLE
Unable to change volume level. Wrong output device selected.

### ISSUE THREAD

**Issue by RockafellaJaz** [josh-richardson/cadmus#20] opened 2020-07-01 16:01 UTC
I am using Linux Mint 19.3 XFCE.

When I enable noise suppression, cadmus seems to set my default output device to 'LADSPA Plugin Suppressor for Voice (Mono) on Null Output. Although I can hear audio this means when adjusting the volume with the media keys or the slider in the PulseAudio Plugin (xfce4-pulseaudio-plugin) the sound level is not changed.

To fix this.
After enabling the noise suppression, I have to re-select the sound output device I wish to use in the PulseAudio Plugin.
Then open up pavucontrol and under the Playback tab set
 'LADSPA Stream on' back to 'Null Output' 
and 
'Loopback of Denoised Microphone on' back to 'LADSPA Plugin Noise Suppressor for Voice (Mono) on Null Output'.

Is this just some kind of xfce4-pulseaudio-plugin quirk or a bug?

**Comment by josh-richardson** [comment] 2020-07-10 02:06
I'm reasonably certain that this it to do with how Camus currently changes your default output, and is likely a dupe of this one: https://github.com/josh-richardson/cadmus/issues/9

I'm hoping that this PR will address it: https://github.com/josh-richardson/cadmus/pull/26

**Closed as completed** 2020-07-10 02:06 UTC
