### ISSUE TITLE
Registers an output device instead of an input device.

### ISSUE THREAD

**Issue by Aurailus** [josh-richardson/cadmus#17] opened 2020-06-30 05:46 UTC
When I enable noise suppression on XUbuntu 16.04, it registers a new Output Device titled Null Output, and not a new Input Device.

**Comment by xfalcox** [comment] 2020-06-30 18:40
Same thing for me on Ubuntu 20.04

**Comment by DBerke** [comment] 2020-07-01 09:47
I'm getting the same behavior. I downloaded the latest .deb from the releases page on Debian 10 Stable and get two new outputs upon selecting a microphone to denoise, "Null Output" and "LADSPA Plugin Noise Suppressor for Voice (Mono) on Null Output", with nothing new in Input Devices.

**Comment by AdamGalt** [comment] 2020-07-01 11:30
Seeing the same on Kubuntu 18.04. However, after testing with Audacity I can confirm it's working correctly when enabled.
Noise is clearly cut from the mic looking at the waveform and background sounds are noticeably cut down in the audio playback.

**Comment by CBSkarmory** [comment] 2020-07-02 02:51
> When I enable noise suppression on XUbuntu 16.04, it registers a new Output Device titled Null Output, and not a new Input Device.

Did you enable it for something like `Monitor of Built-in Audio Analog Stereo`?
If so, try choosing `Built-in Audio Analog Stereo` instead
![image](https://user-images.githubusercontent.com/26392939/86311226-861a5900-bbe5-11ea-8643-00518f4602e6.png)

**Comment by CBSkarmory** [comment] 2020-07-02 03:03
> I'm getting the same behavior. I downloaded the latest .deb from the releases page on Debian 10 Stable and get two new outputs upon selecting a microphone to denoise, "Null Output" and "LADSPA Plugin Noise Suppressor for Voice (Mono) on Null Output", with nothing new in Input Devices.


It works for me (mostly, a restart is required here & there) and those options show up in addition to the denoised mic in input devices (though it's a monitor rather than a virtual device, which apparently doesn't work with some applications).
(PulseAudio Volume Control::output devices)This shows the two you mentioned:
![image](https://user-images.githubusercontent.com/26392939/86311400-f0cb9480-bbe5-11ea-96fb-ab40de7ce42e.png)

(PulseAudio Volume Control::input devices::Show all input devices) shows the denoised mic:
![image](https://user-images.githubusercontent.com/26392939/86311533-38eab700-bbe6-11ea-837d-a4f017c52fba.png)

Indeed in settings::Sound it doesn't show up, but it works fine in audacity
![image](https://user-images.githubusercontent.com/26392939/86311737-aa2a6a00-bbe6-11ea-9c94-441532ed223e.png)

**Comment by josh-richardson** [comment] 2020-07-10 20:16
This has been addressed in #26 and as such I'm closing this issue. Please do re-open it if the new version doesn't fully solve this issue.

**Closed as completed by josh-richardson** 2020-07-10 20:16 UTC
